apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: flock-web
build:
  artifacts:
    - image: wcygan/flock-web
      context: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
deploy:
  kubectl: {}