apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: flock

# This configures the application
requires:
  - configs:
      - flock-api-configuration
    path: flock-api/skaffold.yaml
  - configs:
      - ingress-configuration
    path: ingress/skaffold.yaml
  - configs:
      - flock-web
    path: flock-web/skaffold.yaml

profiles:
  # This configures the infrastructure required for the application
  - name: infrastructure
    patches:
      - op: replace
        path: /requires
        value:
          - configs:
              - postgres-operator-installation
            path: flock-db/skaffold.yaml
          - configs:
              - flock-db-configuration
            path: flock-db/skaffold.yaml
          - configs:
              - keycloak-installation
            path: flock-kc/skaffold.yaml
          - configs:
              - ingress-installation
            path: ingress/skaffold.yaml