apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: flock

# This configures the application
requires:
  - configs:
      - flock-db-configuration
    path: flock-db/skaffold.yaml
  - configs:
      - flock-api-configuration
    path: flock-api/skaffold.yaml
  - configs:
      - keycloak-configuration
    path: keycloak/skaffold.yaml

profiles:
  # This configures the infrastructure required for the application
  - name: infrastructure
    patches:
      - op: replace
        path: /requires
        value:
          - configs:
              - postgres-operator-installation
            path: flock-db/skaffold.yaml