apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: flock

# This configures the application
requires:
  - configs:
      - flock-api-configuration
    path: flock-api/skaffold.yaml
  - configs:
      - ingress-configuration
    path: ingress/skaffold.yaml
  - configs:
      - flock-auth-service-configuration
    path: flock-auth-service/skaffold.yaml
  - configs:
      - flock-profile-service-configuration
    path: flock-profile-service/skaffold.yaml

profiles:
  # This configures the infrastructure required for the application
  - name: infrastructure
    patches:
      - op: replace
        path: /requires
        value:
          - configs:
              - secrets
            path: secrets/skaffold.yaml
          - configs:
              - kube-prometheus-stack
            path: monitoring/skaffold.yaml
          - configs:
              - postgres-operator-installation
            path: flock-auth/skaffold.yaml
          - configs:
              - flock-auth-configuration
            path: flock-auth/skaffold.yaml
          - configs:
              - ingress-installation
            path: ingress/skaffold.yaml