apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: flock

requires:
  - configs:
      - flock-db-configuration
    path: flock-db/skaffold.yaml
  - configs:
      - flock-api-configuration
    path: flock-api/skaffold.yaml

profiles:
  - name: bootstrap
    patches:
      - op: replace
        path: /requires
        value:
          - configs:
              - postgres-operator-installation
            path: flock-db/skaffold.yaml