apiVersion: apps/v1
kind: Deployment
metadata:
  name: flock-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flock-auth-service
  template:
    metadata:
      labels:
        app: flock-auth-service
    spec:
      containers:
        - name: flock-auth-service
          image: wcygan/flock-auth-service:latest-v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 2
            failureThreshold: 5
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: flock-auth-service
spec:
  selector:
    app: flock-auth-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flock-auth-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flock-auth-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50