name: {{SERVICE_NAME}}

on:
  push:
    branches: [ main ]
    paths:
      - "{{SERVICE_NAME}}/**"
  pull_request:
    branches: [ main ]
    paths:
      - "{{SERVICE_NAME}}/**"

jobs:
  # 1) Build & test on Pull Request
  build-{{SERVICE_NAME}}-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('{{SERVICE_NAME}}/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Optional: Lint/test steps
      # - name: Go deps
      #   run: |
      #     cd {{SERVICE_NAME}}
      #     go mod download
      #
      # - name: Go Lint
      #   run: |
      #     cd {{SERVICE_NAME}}
      #     golangci-lint run
      #
      # - name: Go Test
      #   run: |
      #     cd {{SERVICE_NAME}}
      #     go test ./...

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: ./{{SERVICE_NAME}}
          file: ./{{SERVICE_NAME}}/Dockerfile
          load: true  # Build for local testing
          tags: wcygan/{{SERVICE_NAME}}:pr
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # 2) Build & Push on push to main
  build-and-push-{{SERVICE_NAME}}:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('{{SERVICE_NAME}}/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Optional: Lint/test steps
      # - name: Go deps
      #   run: |
      #     cd {{SERVICE_NAME}}
      #     go mod download
      #
      # - name: Go Lint
      #   run: |
      #     cd {{SERVICE_NAME}}
      #     golangci-lint run
      #
      # - name: Go Test
      #   run: |
      #     cd {{SERVICE_NAME}}
      #     go test ./...

      - name: Determine version
        id: version
        run: echo "VERSION=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

      - name: Build and Push the {{SERVICE_NAME}} image
        uses: docker/build-push-action@v5
        with:
          context: ./{{SERVICE_NAME}}
          file: ./{{SERVICE_NAME}}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=wcygan/{{SERVICE_NAME}}:latest
          cache-to: type=inline
          tags: |
            wcygan/{{SERVICE_NAME}}:latest
            wcygan/{{SERVICE_NAME}}:${{ env.VERSION }}
