postgresql:
  enabled: false

externalDatabase:
  host: flock-db-rw.default.svc.cluster.local
  port: 5432
  user: flockuser
  password: flock123
  database: flockdb

replicaCount: 1

auth:
  adminUser: admin
  adminPassword: password

keycloakConfigCli:
  enabled: true
  configuration:
    flock.json: |
      {
        "realm": "flock",
        "enabled": true,
        "registrationAllowed": true,
        "loginWithEmailAllowed": true,
        "duplicateEmailsAllowed": false,
        "resetPasswordAllowed": true
      }

ingress:
  enabled: true
  ingressClassName: tailscale
  hostname: auth.<custom-domain>.ts.net
  tls: true
  extraTls:
    - hosts:
        - auth.<custom-domain>.ts.net
  paths:
    - path: /
      pathType: Prefix
      backend:
        name: keycloak
        port:
          name: http

production: false
proxy: edge

## Disable TLS
https:
  enabled: false

service:
  type: ClusterIP
  port: 8080

extraEnvVars:
  - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KC_PROXY
    value: "edge"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KEYCLOAK_PRODUCTION
    value: "false"
  - name: KC_HTTP_PORT
    value: "8080"

# Resource limits for development
resources:
  limits:
    memory: "1Gi"
    cpu: "1000m"
  requests:
    memory: "512Mi"
    cpu: "250m"

# Probes configuration
startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 60
  successThreshold: 1

livenessProbe:
  enabled: true
  initialDelaySeconds: 300
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1
