apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: kube-prometheus-stack
deploy:
  helm:
    releases:
      - name: kube-prometheus
        namespace: monitoring
        createNamespace: true
        repo: https://prometheus-community.github.io/helm-charts
        remoteChart: kube-prometheus-stack
        version: 66.3.1
        setValues:
          grafana:
            adminPassword: "admin"
          prometheus:
            prometheusSpec:
              retention: "7d"
