# KeyCloak Values

postgresql:
  enabled: false  # Disable the default PostgreSQL deployment

externalDatabase:
  host: flock-db-rw.default.svc.cluster.local
  port: 5432
  user: flockuser
  password: flock123
  database: flockdb

replicaCount: 1 # Number of Keycloak instances to deploy