apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: flock-kc
spec:
  instances: 1
  db:
    vendor: postgres
    host: flock-db-rw.default.svc.cluster.local
    port: 5432
    database: flockdb
    usernameSecret:
      name: flockuser-secret
      key: username
    passwordSecret:
      name: flockuser-secret
      key: password
  http:
    httpEnabled: true
    httpPort: 8180
    httpsPort: 8543
    tlsSecret: kc-tls-secret
  hostname:
    strict: false