apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: keycloak-installation
manifests:
  rawYaml:
    - kc-tls-secret.yaml
    - keycloak-crd-1.yaml
    - keycloak-crd-2.yaml
    - keycloak-operator.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: keycloak-configuration
manifests:
  rawYaml:
    - keycloak-flock-deployment.yaml
deploy:
  kubectl: {}