apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: keycloak-installation
deploy:
  helm:
    releases:
      - name: keycloak
        repo: https://charts.bitnami.com/bitnami
        remoteChart: keycloak
        version: 24.0.0
        namespace: keycloak
        createNamespace: true
        wait: true
        valuesFiles:
          - values.yaml