apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: keycloak-crds
manifests:
  rawYaml:
    - keycloak-crd-1.yaml
    - keycloak-crd-2.yaml
deploy:
  kubectl:
    hooks:
      after:
        - host:
            command: ["kubectl", "wait", "--for=condition=Established", "--timeout=300s", "crd/keycloaks.k8s.keycloak.org"]
        - host:
            command: ["kubectl", "wait", "--for=condition=Established", "--timeout=300s", "crd/keycloakrealmimports.k8s.keycloak.org"]
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: keycloak-operator-installation
requires:
  - configs:
      - keycloak-crds
manifests:
  rawYaml:
    - kc-tls-secret.yaml
    - keycloak-operator.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: keycloak-configuration
requires:
  - configs:
      - keycloak-operator-installation
manifests:
  rawYaml:
    - keycloak-flock-deployment.yaml
deploy:
  kubectl: {}
