# Air configuration for live-reloading during development

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/flock-post-service ./cmd/main.go"
  bin = "./tmp/flock-post-service"
  delay = 1000
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]

[color]
  main = "magenta"
  watcher = "cyan"

[log]
  time = false