cluster:
  name: flock-auth
  instances: 1
  storage:
    storageClass: "openebs-hostpath"
    size: "4Gi"
  bootstrap:
    initdb:
      database: authentication
      owner: flockuser
      secret:
        name: flockuser-secret
      postInitSQL:
        - ALTER ROLE flockuser WITH LOGIN;
  resources:
    limits:
      cpu: 500m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 4Gi