apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: flock-db
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: flockdb
      owner: flockuser
      secret:
        name: flockuser-secret
      postInitSQL:
        - ALTER ROLE flockuser WITH LOGIN;
