apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: postgres-operator-installation
deploy:
  helm:
    releases:
      - name: cnpg-operator
        repo: https://cloudnative-pg.github.io/charts
        remoteChart: cloudnative-pg
        version: 0.23.0
        namespace: cnpg-system
        createNamespace: true
        wait: true
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: flock-db-configuration
deploy:
  helm:
    releases:
      - name: cnpg-cluster
        repo: https://cloudnative-pg.github.io/charts
        remoteChart: cluster
        version: 0.1.3
        namespace: cnpg-system
        createNamespace: true
        wait: true
        valuesFiles:
          - values.yaml