apiVersion: apps/v1
kind: Deployment
metadata:
  name: flock-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flock-web
  template:
    metadata:
      labels:
        app: flock-web
    spec:
      containers:
      - name: flock-web
        image: flock-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20 