apiVersion: apps/v1
kind: Deployment
metadata:
  name: flock-web
  namespace: default
  labels:
    app: flock-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flock-web
  template:
    metadata:
      labels:
        app: flock-web
    spec:
      containers:
        - name: flock-web
          image: wcygan/flock-web:svelte-v2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: NODE_ENV
              value: "production"
            - name: VITE_PUBLIC_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: tailnet-domain
                  key: api-origin
            - name: VITE_PUBLIC_APP_URL
              valueFrom:
                secretKeyRef:
                  name: nextauth-config
                  key: url
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"