apiVersion: apps/v1
kind: Deployment
metadata:
  name: flock-web
  namespace: default
  labels:
    app: flock-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flock-web
  template:
    metadata:
      labels:
        app: flock-web
    spec:
      containers:
        - name: flock-web
          image: wcygan/flock-web:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: NEXT_PUBLIC_FLOCK_API_URL=
              valueFrom:
                secretKeyRef:
                  name: tailnet-domain
                  key: api-origin
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: client_id
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: client_secret
            - name: KEYCLOAK_ISSUER
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: issuer
            # NextAuth configuration
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: nextauth-config
                  key: url
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: nextauth-config
                  key: secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
