name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-flock-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('flock-web/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Build flock-web Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./flock-web
          file: ./flock-web/Dockerfile
          load: true
          tags: flock-web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-flock-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('flock-api/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build flock-api Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./flock-api
          file: ./flock-api/Dockerfile
          load: true
          tags: flock-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
