name: flock-profile-service

on:
  push:
    branches: [ main ]
    # Only trigger the image generation action code for artifacts change
    paths:
      - "flock-profile-service/**/*.go"
      - "flock-profile-service/**/*.mod"
      - "flock-profile-service/**/*.sum"
  pull_request:
    branches: [ main ]
    paths:
      - "flock-profile-service/**"

jobs:
  # 1) Build & test on Pull Request
  build-flock-profile-service-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('flock-profile-service/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Optional: Lint/test steps
      # - name: Go deps
      #   run: |
      #     cd flock-profile-service
      #     go mod download
      #
      # - name: Go Lint
      #   run: |
      #     cd flock-profile-service
      #     golangci-lint run
      #
      # - name: Go Test
      #   run: |
      #     cd flock-profile-service
      #     go test ./...

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: ./flock-profile-service
          file: ./flock-profile-service/Dockerfile
          load: true  # Build for local testing
          tags: wcygan/flock-profile-service:pr
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # 2) Build & Push on push to main
  build-and-push-flock-profile-service:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('flock-profile-service/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Optional: Lint/test steps
      # - name: Go deps
      #   run: |
      #     cd flock-profile-service
      #     go mod download
      #
      # - name: Go Lint
      #   run: |
      #     cd flock-profile-service
      #     golangci-lint run
      #
      # - name: Go Test
      #   run: |
      #     cd flock-profile-service
      #     go test ./...

      - name: Determine version
        id: version
        run: echo "VERSION=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

      - name: Build and Push the flock-profile-service image
        uses: docker/build-push-action@v5
        with:
          context: ./flock-profile-service
          file: ./flock-profile-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=wcygan/flock-profile-service:latest
          cache-to: type=inline
          tags: |
            wcygan/flock-profile-service:latest
            wcygan/flock-profile-service:${{ env.VERSION }}
