name: Build and Push Container Images

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push the flock-api image
        uses: docker/build-push-action@v5
        with:
          context: ./flock-api
          file: ./flock-api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: wcygan/flock-api:latest
          cache-from: type=registry,ref=wcygan/flock-api:latest
          cache-to: type=inline